name: Pull Request Labeler
on: [pull_request_target]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - name: Labeler
      uses: estrada9166/labeler@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
